import windowlineImg from '@/assets/images/Projects/Windowline.jpg';
import reehynImg from '@/assets/images/Projects/reehyn.jpg';
import ayursainImg from '@/assets/images/Projects/b61e53161231677.63c182bf577a9.jpg';
import s3lightingImg from '@/assets/images/Projects/451572687_987102726543156_9122364744555825506_n.jpg';
import { v4 as itemId } from 'uuid';

export const projectsItems = [
    {
        name: "Window Line UAE",
        type: "web",
        work: "Web Site",
        photoUrl: windowlineImg,
        projectDetails: 'https://www.windowlineuae.com/',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
        
        
    },
    {
        name: "Reehyn Perfumes",
        type: "web",
        work: "Web Site",
        photoUrl: reehynImg,
        projectDetails: 'https://www.reehynperfumes.com/',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Ayursain",
        type: "designing",
        work: "Branding",
        photoUrl: ayursainImg,
        projectDetails: 'https://www.behance.net/gallery/161231677/Ayursain-Logo-Creation-Branding',
        id : itemId(),
        images : [
            'https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/b61e53161231677.63c182bf577a9.jpg',
           'https://mir-s3-cdn-cf.behance.net/project_modules/fs/44bcc2161234407.63c18b9dd9597.jpg',
           'https://mir-s3-cdn-cf.behance.net/project_modules/fs/c384ee161231677.63c182bf55efc.jpg',
        ],
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "3S Lighting & Solutions",
        work: "Social Media Poster",
        type: "designing",
        photoUrl: s3lightingImg,
        projectDetails: 'https://www.instagram.com/p/C9euTS3TK2n/?hl=en',
        id : itemId(),
         description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Miamish Karak Tea Powder",
        work: "Package Design",
        type: "designing",
        photoUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/99636f173416633.64903de9dd47d.jpg",
        projectDetails: 'https://www.behance.net/gallery/173416633/Miamish-Karak-Tea-Powder-Design',
        id : itemId(),
        images : [
            'https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/99636f173416633.64903de9dd47d.jpg',
            'https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/6c7b2d173416633.64903de9dfbe9.jpg',
            'https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/7df276173416633.64903de9de775.jpg',
            'https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/b81c7f173416633.64903de9e13f2.jpg'
        ],
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Taj Muwaileh",
        work: "Brochure Design",
        type: "designing",
        photoUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ff222f160112463.63ad3882efb7d.jpg",
        projectDetails: 'https://www.behance.net/gallery/160112463/Brochure',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Telal",
        work: "Wall Poster Design",
        type: "designing",
        photoUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/e82a20156114505.6361569942bc8.jpg",
        projectDetails: 'https://www.behance.net/gallery/156114505/Wallpost-Design',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Al Madina Beauty Fair Booklet Design",
        work: "Booklet Design",
        type: "designing",
        photoUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/7c6299171489595.646f62b0124df.jpg",
        projectDetails: 'https://www.behance.net/gallery/171489595/Booklet-Design',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
    {
        name: "Al Madina Offer Booklet Design",
        work: "Offer Booklet Design",
        type: "designing",
        photoUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/22ced6171489285.646f61d392b48.jpg",
        projectDetails: 'https://www.behance.net/gallery/171489285/Supermarket-Offer-Booklet-Design',
        id : itemId(),
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus facilisis sagittis. Aliquam lacus metus, commodo auctor erat ac, lobortis lobortis elit. Donec ac mauris id orci vulputate porta. Proin dolor enim, dapibus et pretium sit amet, malesuada non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel tortor ornare, tristique sapien at, placerat justo. Aenean egestas eget massa a consectetur. Integer blandit, magna vestibulum consectetur viverra, libero risus rhoncus tortor, sit amet sollicitudin nulla nisl eget massa. Morbi bibendum libero ex, et consectetur velit mollis consequat. In pulvinar lacus at ante molestie, sed malesuada nisl tincidunt. Suspendisse potenti. Phasellus leo arcu, aliquet nec odio at, placerat rutrum nulla. Etiam a sollicitudin sapien, elementum cursus lectus. Integer tincidunt odio non felis pharetra, eu hendrerit purus hendrerit. Proin ullamcorper odio sit amet nibh efficitur, in ornare massa eleifend. Curabitur lorem tellus, bibendum tristique tincidunt vel, rutrum sit amet nisi. Vestibulum hendrerit, dolor et efficitur ullamcorper, metus lacus fringilla mi, id malesuada est tellus sit amet tortor. Aliquam ut justo ac urna ullamcorper mollis a et enim. Nullam semper justo id bibendum pharetra. Cras tempus mi sed hendrerit interdum. Fusce porttitor est et scelerisque mattis. Quisque volutpat tellus nec odio pretium ullamcorper. Curabitur convallis neque porta, vehicula lorem vitae, sagittis eros. Integer elementum congue diam, quis pulvinar elit euismod in. Nulla consectetur commodo fringilla. Nunc pellentesque lorem eu semper pharetra. Phasellus porttitor nisl vel elit imperdiet scelerisque. Ut varius purus vitae metus egestas, at lobortis neque consectetur. Aenean lacinia diam lacus, et molestie massa viverra sit amet. Donec commodo lorem eget massa tempor, ac finibus nulla ultrices. Nulla ultrices nulla magna, eu sodales est finibus ut. Proin maximus malesuada magna, a finibus nunc ornare non. Nulla quis nunc nisl. Cras odio nisi, lobortis in sagittis maximus, lobortis eget sapien. Nullam augue turpis, lacinia quis auctor dictum, finibus sit amet ipsum. Donec et luctus felis, vitae sodales purus. Vivamus maximus eros nulla, efficitur cursus ante mattis quis. Curabitur scelerisque risus a eros volutpat dignissim. Donec vel nulla sollicitudin, accumsan nisl a, varius tortor."
    },
];
